sudo: required
dist: trusty
language: node_js
node_js: 7
branches:
  only:
  - master
  - develop
deploy:
  provider: heroku
  app:
    master: quoridor-jees
    develop: jees-quoridor
  api_key:
    develop:
      secure: t6wC54YyE985ljPMNNwykkd+3Jrpfzuo4tN+5h9+AIh9jlPIW5RagmoeKqhF6dFUA/DXRNNGlb7TiXykVoLMnnD+a+fH2me+dfSspLGMae+vxdOEpfhkgyPOtCoJUfZmsvq+zo2asnz7uSFdpmsQU8zIaFGy8okI/36eSosG0wKjGfCa0AZynkf0JggjB2VBgr2YcL0rN2/jSLn4zdLiWaoUZBw2F9UyLKVbK4i+5Jx4/Ffxtzh17LxEQnPb90T/Lkemc7ucs4U5PeFAag9Z0LBz6p4B1BWquFCo4dzTA3QZ0wzkpiVbNCWsk4RfXKkr7WKxwOmBm+6+K4EgX1nr/NNVCwkuGsF1rHRDPD08MUcFzWCEf8b3XUjYM9U41GMol+wxrbOSVIF/WFyegHqye8TeRjqhYcjBq6jVKIj3UmxgaaVH0LYeobKZonSynAZaKlUrPI8OGKj50W34P8BQks/Zr9wr25RQE5YyWeWCdSxGOEi9odc2KbsRbr7wh7V/ubMihsjDqxMmmGi40AJpJZxLNGGJvR0Ysn30ASTPooKoEOvBrymcVncDEg4a5h8DrF8pt6EI/s7ULFhKFqyS11tD/+8/TyGHEq25qRrLcJKd4bPHUQdPzNeN/rOGH8beAVuL1+9Ag2x2zZizzP3R44wKUjMwuxJElgNE6NoWa4g=
    master:
      secure: YV+IxYz1qyIy+94MWaYujq/Yri1eP2ozS1Cd85O6+ERG5vMUK1kp3ZEJvZkXJ2vAhF3Z0r0ctHMij5YXZO7WYvAei4/Or+EwPJXX4JbHklFWu5RxvdZgZQS6MtxaxMcuuakiutVDC4wG2NUtV307aOTXaVKIbxos8RHffuQCGfj6B3hcfGEV3ro6uSXL+m7NBR9UQhXte+yhhL69mUW1UgkwX4L7xYaqTWIj2HfSM1S6mv3UJzykfOxGJHZvdYs71UIx6JSbVv5ONjT8stBViecn2uLSQD6V3WgQmpeSgK8B5JOsaQAqYo1Q4pxFr6FrIw4q8olPCiZ/yb4MOll+Q7j0EwhHThOZrYe8NJhSczYdnFsj7cOxlFDRvYTO5x0xcB1Z8H9J0Wnic22CpKlTx4tSEnR2pXSt2WJL4aRLDt9S2X7hw+4LmLl7DLnOnBJR/hlFuEWQfVcO3QRcjld3upCLO7LeLswAGT6ngikyWMOZkiR/zjVJLs1Xzxnd1JZ+OcujF9xCDxM5pqGppg67zj+OoPZVFgssvkS18jVXY3gURPZCB9Enq7OWdNgsvsCa91o+/kqOjtNK89PmyAJOsPCTgOI0KovWuGlRuTUaJCp/QDGqenE2pQTm+b21HpMXOqK44CwT1ZrpJNb8NhVUw2Hp6Rioeinv9H5+z58ejV0=
