sudo: required
dist: trusty
language: node_js
node_js: 7
branches:
  only:
  - master
deploy:
  provider: heroku
  app:
    master: quoridor-jees
  api_key:
    master:
      secure: t6wC54YyE985ljPMNNwykkd+3Jrpfzuo4tN+5h9+AIh9jlPIW5RagmoeKqhF6dFUA/DXRNNGlb7TiXykVoLMnnD+a+fH2me+dfSspLGMae+vxdOEpfhkgyPOtCoJUfZmsvq+zo2asnz7uSFdpmsQU8zIaFGy8okI/36eSosG0wKjGfCa0AZynkf0JggjB2VBgr2YcL0rN2/jSLn4zdLiWaoUZBw2F9UyLKVbK4i+5Jx4/Ffxtzh17LxEQnPb90T/Lkemc7ucs4U5PeFAag9Z0LBz6p4B1BWquFCo4dzTA3QZ0wzkpiVbNCWsk4RfXKkr7WKxwOmBm+6+K4EgX1nr/NNVCwkuGsF1rHRDPD08MUcFzWCEf8b3XUjYM9U41GMol+wxrbOSVIF/WFyegHqye8TeRjqhYcjBq6jVKIj3UmxgaaVH0LYeobKZonSynAZaKlUrPI8OGKj50W34P8BQks/Zr9wr25RQE5YyWeWCdSxGOEi9odc2KbsRbr7wh7V/ubMihsjDqxMmmGi40AJpJZxLNGGJvR0Ysn30ASTPooKoEOvBrymcVncDEg4a5h8DrF8pt6EI/s7ULFhKFqyS11tD/+8/TyGHEq25qRrLcJKd4bPHUQdPzNeN/rOGH8beAVuL1+9Ag2x2zZizzP3R44wKUjMwuxJElgNE6NoWa4g=
